title: ky_gough.com
email: kyrangough2019@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ky_gough.com is a small blog created using Jekyll and hosted on GitHub Pages. We host primarily technology related content, however we do write outside of our expertise on music and general opinions. Hope you enjoy!
baseurl: ""
url: "kygough.com"
twitter_username: ky_gough
github_username:  kyg203

# Build settings
theme: minima
plugins:
  - jekyll-feed
  
include:
- images
